services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app.env
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine

  web:
    build: .
    entrypoint: ["/app/docker-entrypoint.sh"]
    command: >
      sh -c "
        while ! nc -z db 5432; do sleep 0.1; done &&
        python manage.py migrate &&
        gunicorn tax_service.wsgi:application --bind 0.0.0.0:8000 --workers 4
      "
    volumes:
      - .:/app
      - ./media:/app/media
      - /var/opt/cprocsp:/var/opt/cprocsp
      - /etc/opt/cprocsp:/etc/opt/cprocsp:ro
    ports:
      - "8000:8000"
    env_file:
      - ./app.env
    depends_on:
      - db
      - redis
    user: root

  worker:
    build: .
    entrypoint: ["/app/docker-entrypoint.sh"]
    command: celery -A tax_service worker -l info
    volumes:
      - .:/app
      - /var/opt/cprocsp:/var/opt/cprocsp
      - /etc/opt/cprocsp:/etc/opt/cprocsp:ro
    env_file:
      - ./app.env
    depends_on:
      - redis
      - db
    user: root

  beat:
    build: .
    entrypoint: ["/app/docker-entrypoint.sh"]
    command: celery -A tax_service beat -l info
    volumes:
      - .:/app
      - /var/opt/cprocsp:/var/opt/cprocsp
      - /etc/opt/cprocsp:/etc/opt/cprocsp:ro
    env_file:
      - ./app.env
    depends_on:
      - redis
      - db
    user: root

volumes:
  postgres_data:
