# Generated by Django 4.2.23 on 2025-07-30 12:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('SIGNED', 'Подписан'), ('UPLOADED', 'Загружен'), ('SENT', 'Отправлен'), ('CONFIRMED', 'Подтвержден'), ('ERROR', 'Ошибка')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('files', models.JSONField(help_text='Массив путей к файлам', verbose_name='Файлы')),
                ('sbis_doc_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID документа в СБИС')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Лог ошибок')),
                ('theme', models.TextField(blank=True, null=True, verbose_name='Тема/примечание')),
                ('svedeniya', models.JSONField(verbose_name='Служебные сведения')),
                ('checksum', models.JSONField(verbose_name='Контрольные суммы')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('format_version', models.CharField(max_length=20, verbose_name='Версия формата')),
                ('period', models.JSONField(blank=True, null=True, verbose_name='Период')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(verbose_name='Тело запроса')),
                ('response_status', models.PositiveIntegerField(verbose_name='Статус ответа')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='reports.document', verbose_name='Документ')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SIGN', 'Подписание'), ('UPLOAD', 'Загрузка'), ('SEND', 'Отправка'), ('STATUS_CHECK', 'Проверка статуса')], max_length=20, verbose_name='Тип события')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Детали')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reports.document', verbose_name='Документ')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='document',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.recipient', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='document',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reporttype', verbose_name='Тип отчета'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='reports_doc_status_eec4f8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='reports_doc_created_3be8ad_idx'),
        ),
    ]
