# Generated by Django 5.2.6 on 2025-09-29 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=12)),
                ('container_path', models.CharField(max_length=255, unique=True)),
                ('thumbprint', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('source', models.CharField(choices=[('LOCAL', 'Local'), ('MEGA', 'Mega')], max_length=20)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('inn', 'container_path')},
            },
        ),
        migrations.CreateModel(
            name='CertificateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='MailCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=12)),
                ('period_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('attachments_meta', models.JSONField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('cert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.certificate')),
            ],
            options={
                'unique_together': {('inn', 'period_date')},
            },
        ),
    ]
