# Generated by Django 5.2.8 on 2025-12-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_certificate_certificateauditlog_mailcache'),
    ]

    operations = [
        # 1) Добавляем новые поля к Certificate
        migrations.AddField(
            model_name='certificate',
            name='csptest_name',
            field=models.CharField(
                blank=True,
                null=True,
                unique=True,
                max_length=255,
                verbose_name='Имя контейнера (csptest)',
                help_text='Например: \\\\.\\HDIMAGE\\c73dd937f-bcbf-6d48-f0c7-8bccbbb8297',
            ),
        ),
        migrations.AddField(
            model_name='certificate',
            name='has_private_key',
            field=models.BooleanField(
                default=False,
                verbose_name='Есть приватный ключ',
            ),
        ),
        migrations.AddField(
            model_name='certificate',
            name='hdimage_path',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=255,
                verbose_name='Путь контейнера (uMy)',
                help_text='Например: HDIMAGE\\\\9715472576\\4698',
            ),
        ),
        migrations.AddField(
            model_name='certificate',
            name='last_seen_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Последний раз обнаружен',
            ),
        ),
        migrations.AddField(
            model_name='certificate',
            name='not_after',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Действителен по',
            ),
        ),
        migrations.AddField(
            model_name='certificate',
            name='not_before',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Действителен с',
            ),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='source',
            field=models.CharField(
                choices=[('LOCAL', 'Local'), ('MEGA', 'Mega')],
                max_length=20,
                verbose_name='Источник',
            ),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='thumbprint',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=64,
                db_index=True,
                verbose_name='SHA1 отпечаток',
            ),
        ),

        # 2) Меняем unique_together (container_path ещё существует)
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('inn', 'csptest_name')},
        ),

        # 3) Теперь можно удалить старое поле container_path
        migrations.RemoveField(
            model_name='certificate',
            name='container_path',
        ),
    ]
